project:
  type: website
  output-dir: docs

website:
  title: "Sam Kirkham and Jonas Shiel - Final Project"
  description: "Political Data Analysis"

  navbar:
    background: primary
    left:
      - text: "Write Up"
        href: Final.html
      - text: "Demo"
        href: Package_Demo.html
      - text: "Projects"
        menu:
          - text: "Final"
            href: Final.html
          - text: "Demo"
            href: Package_Demo.html
    right:
      - icon: github
        href: https://github.com/Sam-Kirkham
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-kirkham-1b3730385/

  sidebar:
    - title: "Projects"
      contents:
        - Final.html
        - Package_Demo.html

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
