project:
  type: website

website:
  output-dir: docs  # <- This is what you want for GitHub Pages


website:
  title: "Sam Kirkham and Jonas Shiel - Final Project"
  description: "Political Data Analysis"
  
  navbar:
    background: primary
    left:
      - text: "Final"
        href: Final.qmd
      - text: "Demo"
        href: Package_Demo.qmd
      - text: "Projects"
        menu:
          - text: "Final"
            href: Final.qmd
          - text: "Demo"
            href: Package_Demo.qmd
    right:
      - icon: github
        href: https://github.com/Sam-Kirkham
      - icon: linkedin
        href: https://www.linkedin.com/in/samuel-kirkham-1b3730385/
        

  sidebar:
    - title: "Projects"
      contents:
        - Final.qmd
        - Package_Demo.qmd

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true
    code-tools: true
    css: styles.css
